# travis.CI YML config file

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  
# install dependencies
install:
  - pip install pyspeedtest urllib3
  - pip install pyinstaller  # only for compiling here, not needed
  
# do it!
jobs:
  include:
    - stage: build
      script: make all
    - stage: test
      script: echo "Ignore this."
    - stage: lint
      install:
        - pip install flake8-diff
      script:
        - >
            git fetch origin $TRAVIS_BRANCH:$TRAVIS_BRANCH --depth 1;
            flake8-diff -v -v -v $TRAVIS_BRANCH;

stages:
  - lint
  - build
