# name
name: PySpeedTest Documentation

# description
description: Documentation for the internet speed tester.

# base URL
baseurl: /docs

# site theme
theme: jekyll-theme-minimal

# author
author: Michael Turnbull
author_email: mishaturnbull@gmail.com

show_downloads: true
